---
extends: default

rules:
  line-length:
    max: 200
    level: warning
  truthy:
    allowed-values: ['true', 'false', 'on', 'off']
    check-keys: false
  comments:
    min-spaces-from-content: 1
  comments-indentation: disable
  document-start: disable
  indentation:
    spaces: 2
    indent-sequences: consistent
  braces:
    max-spaces-inside: 1

ignore: |
  node_modules/
  .venv/
  custom-addons/jorels-addons/
  jorels-addons/
