{
    'name': 'Tableros de Gestión',
    'version': '19.0.1.0.0',
    'summary': 'Tableros financieros con KPIs para contabilidad, presupuesto y activos',
    'category': 'Accounting/Accounting',
    'author': 'Manuel Caro',
    'license': 'LGPL-3',
    'depends': [
        'board',
        'account',
        'co_accounting_extended',
        'account_profit_loss',
        'account_cash_flow',
        'account_aged_receivable',
        'account_aged_payable',
        'account_balance_sheet',
        'co_budget',
        'co_fixed_assets',
        'co_payroll',
        'co_warehouse_extended',
        'club_core',
        'club_access_control',
        'club_pqr',
        'club_guests',
        'club_affiliate_billing',
    ],
    'data': [
        'security/ir.model.access.csv',
        'views/finance_dashboard_views.xml',
        'views/finance_board_view.xml',
        'views/payroll_dashboard_views.xml',
        'views/payroll_board_view.xml',
        'views/purchase_dashboard_views.xml',
        'views/purchase_board_view.xml',
        'views/club_dashboard_views.xml',
        'views/club_board_view.xml',
        'views/co_menus.xml',
    ],
    'installable': True,
    'auto_install': False,
    'application': False,
}
