[options]
addons_path = /odoo/odoo/addons,/odoo/addons,/mnt/jorels-addons,/mnt/custom-addons
; DB connection is overridden by CLI args from entrypoint
db_host = False
db_port = False
db_user = False
db_password = False
db_name = False
logfile = False
log_level = info
; Production settings
list_db = False
proxy_mode = True
without_demo = all
data_dir = /var/lib/odoo
