[options]
addons_path = /odoo/odoo/addons,/odoo/addons,/mnt/jorels-addons,/mnt/custom-addons
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
db_name = odoo-club19
dbfilter = ^odoo-club19$
logfile = False
log_level = info
data_dir = /var/lib/odoo
