[options]
addons_path = /odoo/odoo/addons,/odoo/addons,/mnt/jorels-addons,/mnt/custom-addons
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
db_name = False
logfile = False
log_level = info
