{
    'name': 'Club Equestrian',
    'version': '18.0.1.0.0',
    'summary': 'Social Country Club — Equestrian Management',
    'description': 'Equestrian module: horses, stalls, arenas, bookings, vet records, feeding schedules.',
    'category': 'Club Management',
    'author': 'Manuel Caro',
    'license': 'LGPL-3',
    'depends': ['club_core'],
    'data': [
        'security/club_equestrian_security.xml',
        'security/ir.model.access.csv',
        'data/sequences.xml',
        'data/cron.xml',
        'views/club_horse_views.xml',
        'views/club_stall_views.xml',
        'views/club_horse_feeding_views.xml',
        'views/club_vet_record_views.xml',
        'views/club_arena_views.xml',
        'views/club_equestrian_booking_views.xml',
        'views/club_equestrian_menus.xml',
        'report/club_feeding_sheet_template.xml',
    ],
    'demo': [
        'data/demo_data.xml',
    ],
    'installable': True,
    'application': False,
}
