{
    'name': 'Goliatt PMS',
    'version': '19.0.2.0.0',
    'summary': 'Full-featured Property Management System for hotels, resorts, and hospitality',
    'description': (
        'Goliatt PMS — Full-featured Property Management System for hotels, '
        'resorts, and hospitality. Inspired by Opera, Cloudbeds, Mews.'
    ),
    'category': 'Hotel Management',
    'author': 'Manuel Caro',
    'license': 'LGPL-3',
    'depends': [
        'base',
        'mail',
        'account',
        'product',
        'stock',
        'point_of_sale',
        'event',
        'contacts',
        'hr',
    ],
    'data': [
        'security/pms_security.xml',
        'security/ir.model.access.csv',
        'data/sequences.xml',
        'data/rms_kiosk_data.xml',
        'views/pms_property_views.xml',
        'views/pms_amenity_views.xml',
        'views/pms_room_type_views.xml',
        'views/pms_room_views.xml',
        'views/pms_guest_views.xml',
        'views/pms_reservation_views.xml',
        'views/pms_rate_plan_views.xml',
        'views/pms_folio_views.xml',
        'views/pms_housekeeping_views.xml',
        'views/pms_channel_views.xml',
        'views/pms_availability_views.xml',
        'views/pms_night_audit_views.xml',
        'views/pms_revenue_rule_views.xml',
        'views/pms_revenue_recommendation_views.xml',
        'views/pms_revenue_log_views.xml',
        'views/pms_kiosk_session_views.xml',
        'views/pms_kiosk_lookup_views.xml',
        'views/pms_property_rms_views.xml',
        'views/pms_reservation_kiosk_views.xml',
        'views/pms_menus.xml',
    ],
    'demo': [
        'data/demo_data.xml',
        'data/demo_rms_kiosk.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'goliatt_pms/static/src/css/dark_theme.css',
            'goliatt_pms/static/src/css/planner.css',
            'goliatt_pms/static/src/xml/planner_template.xml',
            'goliatt_pms/static/src/js/planner.js',
            'goliatt_pms/static/src/xml/dark_mode_toggle.xml',
            'goliatt_pms/static/src/js/dark_mode_toggle.js',
        ],
    },
    'installable': True,
    'application': True,
}
